PIPELINE_LOG_TAG_DEFAULT="interactionism_0"
OUTDIR_DEFAULT="~/WinVideos/interactionism"
PIPELINE_MODE_DEFAULT="custom"

RUN_60S_START=1
RUN_180S_START=1
RUN_60S_END=0
RUN_180S_END=0
RUN_FULL=1

DIVVY_SAMPLING_MODE_DEFAULT="groove"
DIVVY_GROOVE_BPM_DEFAULT="0"

ENABLE_REELS_OVERLAY_STEP=0

PARTICLE_SPARKS_COLOR_MODE_DEFAULT="shobud"
PARTICLE_SPARKS_FLOOD_IN_OUT_DEFAULT=1
PARTICLE_SPARKS_FLOOD_SECONDS_DEFAULT=3.0
PARTICLE_SPARKS_FLOOD_SPAWN_MULT_DEFAULT=4
PARTICLE_SPARKS_FLOOD_EXTRA_SOURCES_DEFAULT=16
PARTICLE_SPARKS_FLOOD_VELOCITY_MULT_DEFAULT=1.5

TITLE_HOOK_TITLE_DEFAULT='// interactionism (hi60s)\n// voidstar'
TITLE_HOOK_SECONDARY_TEXT_DEFAULT='#pedalsteel\n#ambient\n#interactionism\n#voidstar'

ENABLE_GDRIVE_COPY_DEFAULT=0
