### ---------------------------------------------------------------------------
### atemporalism take controls (orchestrator-level)
### ---------------------------------------------------------------------------
PROJECT_DIR_DEFAULT="~/WinVideos/atemporalism"
SOURCES_DIR_DEFAULT="~/WinVideos/atemporalism/sources"
OUTDIR_DEFAULT="~/WinVideos/atemporalism"
COMBINED_INPUT_DEFAULT="~/WinVideos/atemporalism/atemporalism.mp4"
REBUILD_COMBINED_DEFAULT=0
RUN_INDIVIDUAL_DEFAULT=1
INDIVIDUAL_ONLY_DEFAULT=1

### ---------------------------------------------------------------------------
### atemporalism render/take metadata controls (base pipeline)
### ---------------------------------------------------------------------------
PIPELINE_LOG_TAG_DEFAULT="atemporalism"
PIPELINE_MODE_DEFAULT="custom"
START_SECONDS_DEFAULT=""
YOUTUBE_FULL_SECONDS_DEFAULT=""
DETECT_AUDIO_START_END_DEFAULT=1
ENABLE_AUTO_PRETRIM_INPUT_DEFAULT=1
AUTO_PRETRIM_PRE_ROLL_SECONDS_DEFAULT="0.2"
AUTO_PRETRIM_SILENCE_NOISE_DB_DEFAULT="-66dB"
AUTO_PRETRIM_SILENCE_MIN_DURATION_DEFAULT="0.12"

DVDLOGO_VOIDSTAR_PRESET_DEFAULT="subtle"
DVDLOGO_VOIDSTAR_COLORIZE_DEFAULT="false"
DVDLOGO_OPACITY_DEFAULT=0.33
DVDLOGO_LOCAL_POINT_TRACK_OPACITY_DEFAULT=0.33
DVDLOGO_LOCAL_POINT_TRACK_LINK_OPACITY_DEFAULT=0.33 
RESUME_INPUT_CLIP_DEFAULT=""
RESUME_TRIM_SECONDS_DEFAULT="2.0"

RUN_60S_START=0
RUN_180S_START=0
RUN_60S_END=0
RUN_180S_END=0
RUN_FULL=1

DIVVY_SAMPLING_MODE_DEFAULT="groove"
DIVVY_GROOVE_BPM_DEFAULT="0"
DIVVY_60S_START_SAMPLE_SECONDS_DEFAULT=14
DIVVY_60S_START_SEGMENTS_DEFAULT=4
DIVVY_180S_START_SAMPLE_SECONDS_DEFAULT=28
DIVVY_180S_START_SEGMENTS_DEFAULT=6
DIVVY_60S_END_SAMPLE_SECONDS_DEFAULT=14
DIVVY_60S_END_SEGMENTS_DEFAULT=4
DIVVY_180S_END_SAMPLE_SECONDS_DEFAULT=28
DIVVY_180S_END_SEGMENTS_DEFAULT=6
DIVVY_TRUNCATE_TO_FULL_CLIPS_DEFAULT=1

ENABLE_REELS_OVERLAY_STEP=1
ENABLE_TITLE_HOOK_STAGE=1

PARTICLE_SPARKS_COLOR_MODE_DEFAULT="shobud"
PARTICLE_SPARKS_SHOBUD_RENDER_DEFAULT="filled"
PARTICLE_SPARKS_SHOBUD_STROKE_WIDTH_DEFAULT=2.0
PARTICLE_SPARKS_SHOBUD_EDGE_SHIMMER_DEFAULT=0.90
PARTICLE_SPARKS_SHOBUD_EDGE_WIDTH_DEFAULT=2.4
PARTICLE_SPARKS_SHOBUD_PALETTE_DEFAULT="classic"
PARTICLE_SPARKS_SHOBUD_DARK_SUIT_COLOR_DEFAULT="black"
PARTICLE_SPARKS_FLOOD_IN_OUT_DEFAULT=1
PARTICLE_SPARKS_FLOOD_SECONDS_DEFAULT=3.0
PARTICLE_SPARKS_FLOOD_SPAWN_MULT_DEFAULT=4
PARTICLE_SPARKS_FLOOD_EXTRA_SOURCES_DEFAULT=16
PARTICLE_SPARKS_FLOOD_VELOCITY_MULT_DEFAULT=2

TITLE_HOOK_DURATION_DEFAULT=10.0
TITLE_HOOK_DURATION_600_DEFAULT=8.0
TITLE_HOOK_FADE_OUT_DURATION_DEFAULT=1.3
TITLE_HOOK_TITLE_DEFAULT='// atemporalism\n// voidstar'
TITLE_HOOK_SECONDARY_TEXT_DEFAULT='#sho~bud\n#solopedalsteel\n#improvisedmusic\n#atemporalism\n#voidstar'

ENABLE_GDRIVE_COPY_DEFAULT=1
GDRIVE_OUTDIR_DEFAULT="~/GoogleDrive/Music/voidstar/atemporalism"
